export const ASSET_PACK_KEYS = {
    MAIN: "MAIN",
} as const;
export const ASSET_KEYS = {
    PLAYER: "PLAYER",
    ENIMIE_SLIME: "ENIMIE_SLIME",

    COLLISION: "CollisionTiles",
    HUD_NUMBERS: "HUD_NUMBERS",
    FONT_PRESS_START_2P: "FONT_PRESS_START_2P",
    UI_DIALOG: "UI_DIALOG",
    UI_ICONS: "UI_ICONS",
    UI_CURSOR: "UI_CURSOR",
    TORCH_ENIMIE: "TORCH_ENIMIE",
} as const;
export const PLAYER_ANIMATION_KEYS = {
    WALK_DOWN: "player_walk_down",
    WALK_UP: "player_walk_up",
    WALK_SIDE: "player_walk_side",
    IDLE_DOWN: "player_idle_down",
    IDLE_UP: "player_idle_up",
    IDLE_SIDE: "player_idle_side",
    IDLE_HOLD_DOWN: "player_hand_in_air_down",
    IDLE_HOLD_UP: "player_hand_in_air_up",
    IDLE_HOLD_SIDE: "player_hand_in_air_side",
    WALK_HOLD_DOWN: "player_walk_hand_in_air_down",
    WALK_HOLD_UP: "player_walk_hand_in_air_up",
    WALK_HOLD_SIDE: "player_walk_hand_in_air_side",
    LIFT_DOWN: "player_open_chest_down",
    LIFT_UP: "player_open_chest_up",
    LIFT_SIDE: "player_open_chest_side",
    HURT_DOWN: "player_hit_down",
    HURT_UP: "player_hit_up",
    HURT_SIDE: "player_hit_side",
    DIE_DOWN: "player_die_down",
    DIE_UP: "player_die_up",
    DIE_SIDE: "player_die_side",
    SWORD_1_ATTACK_DOWN: "player_atk_1_down",
    SWORD_1_ATTACK_UP: "player_atk_1_up",
    SWORD_1_ATTACK_SIDE: "player_atk_1_side",
} as const;

export const ENIMIE_SLIME_ANIMATION_KEYS = {
    WALK_RIGHT: "enimie_slime_jump_right",
    WALK_LEFT: "enimie_slime_jump_left",
    IDLE_RIGHT: "enimie_slime_idle_right",
    IDLE_LEFT: "enimie_slime_idle_left",
    HURT_RIGHT: "enimie_slime_jump_right",
    HURT_LEFT: "enimie_slime_jump_right",
    HURT_DOWN: "enimie_slime_jump_right",
    HURT_UP: "enimie_slime_jump_right",
    DIE_DOWN: "enimie_slime_death",
    DIE_UP: "enimie_slime_death",
    DIE_LEFT: "enimie_slime_death",
    DIE_RIGHT: "enimie_slime_death",
} as const;
export const ENIMIE_TORCH_ANIMATION_KEYS = {
    WALK_RIGHT: "Run",
    WALK_LEFT: "Run",
    IDLE_RIGHT: "Idle",
    IDLE_LEFT: "Idle",
    HURT_RIGHT: "Idle",
    HURT_LEFT: "Idle",
    HURT_DOWN: "Idle",
    HURT_UP: "Idle",
    DIE_DOWN: "Death",
    DIE_UP: "Death",
    DIE_LEFT: "Death",
    DIE_RIGHT: "Death",
    ATTACK_RIGHT: "Attack_Right",
    ATTACK_LEFT: "Attack_Right",
    ATTACK_UP: "Attack_Up",
    ATTACK_DOWN: "Attack_Down",
} as const;
export const CHARACTER_ANIMATIONS = {
    IDLE_DOWN: "IDLE_DOWN",
    IDLE_UP: "IDLE_UP",
    IDLE_LEFT: "IDLE_LEFT",
    IDLE_RIGHT: "IDLE_RIGHT",
    WALK_DOWN: "WALK_DOWN",
    WALK_UP: "WALK_UP",
    WALK_LEFT: "WALK_LEFT",
    WALK_RIGHT: "WALK_RIGHT",
    IDLE_HOLD_DOWN: "IDLE_HOLD_DOWN",
    IDLE_HOLD_UP: "IDLE_HOLD_UP",
    IDLE_HOLD_LEFT: "IDLE_HOLD_LEFT",
    IDLE_HOLD_RIGHT: "IDLE_HOLD_RIGHT",
    WALK_HOLD_DOWN: "WALK_HOLD_DOWN",
    WALK_HOLD_UP: "WALK_HOLD_UP",
    WALK_HOLD_LEFT: "WALK_HOLD_LEFT",
    WALK_HOLD_RIGHT: "WALK_HOLD_RIGHT",
    LIFT_DOWN: "LIFT_DOWN",
    LIFT_UP: "LIFT_UP",
    LIFT_LEFT: "LIFT_LEFT",
    LIFT_RIGHT: "LIFT_RIGHT",
    HURT_DOWN: "HURT_DOWN",
    HURT_UP: "HURT_UP",
    HURT_LEFT: "HURT_LEFT",
    HURT_RIGHT: "HURT_RIGHT",
    DIE_DOWN: "DIE_DOWN",
    DIE_UP: "DIE_UP",
    DIE_LEFT: "DIE_LEFT",
    DIE_RIGHT: "DIE_RIGHT",
} as const;

export const HEART_TEXTURE_FRAME = {
    NONE: "15",
    FULL: "10",
    EMPTY: "14",
    HALF: "12",
} as const;

export const HEART_ANIMATIONS = {
    LOSE_LAST_HALF: "heart_lose_last_half",
    LOSE_FIRST_HALF: "heart_lost_first_half",
};
