export const ASSET_PACK_KEYS = {
    MAIN: "MAIN",
} as const;
export const ASSET_KEYS = {
    PLAYER: "PLAYER",
} as const;
export const PLAYER_ANIMATION_KEYS = {
    WALK_DOWN: "player_walk_down",
    WALK_UP: "player_walk_up",
    WALK_SIDE: "player_walk_side",
    IDLE_DOWN: "player_idle_down",
    IDLE_UP: "player_idle_up",
    IDLE_SIDE: "player_idle_side",
    IDLE_HOLD_DOWN: "player_hand_in_air_down",
    IDLE_HOLD_UP: "player_hand_in_air_up",
    IDLE_HOLD_SIDE: "player_hand_in_air_side",
    WALK_HOLD_DOWN: "player_walk_hand_in_air_down",
    WALK_HOLD_UP: "player_walk_hand_in_air_up",
    WALK_HOLD_SIDE: "player_walk_hand_in_air_side",
    LIFT_DOWN: "player_open_chest_down",
    LIFT_UP: "player_open_chest_up",
    LIFT_SIDE: "player_open_chest_side",
    HURT_DOWN: "player_hit_down",
    HURT_UP: "player_hit_up",
    HURT_SIDE: "player_hit_side",
    DIE_DOWN: "player_die_down",
    DIE_UP: "player_die_up",
    DIE_SIDE: "player_die_side",
    SWORD_1_ATTACK_DOWN: "player_atk_1_down",
    SWORD_1_ATTACK_UP: "player_atk_1_up",
    SWORD_1_ATTACK_SIDE: "player_atk_1_side",
} as const;

export const CHARACTER_ANIMATIONS = {
    IDLE_DOWN: "IDLE_DOWN",
    IDLE_UP: "IDLE_UP",
    IDLE_LEFT: "IDLE_LEFT",
    IDLE_RIGHT: "IDLE_RIGHT",
    WALK_DOWN: "WALK_DOWN",
    WALK_UP: "WALK_UP",
    WALK_LEFT: "WALK_LEFT",
    WALK_RIGHT: "WALK_RIGHT",
    IDLE_HOLD_DOWN: "IDLE_HOLD_DOWN",
    IDLE_HOLD_UP: "IDLE_HOLD_UP",
    IDLE_HOLD_LEFT: "IDLE_HOLD_LEFT",
    IDLE_HOLD_RIGHT: "IDLE_HOLD_RIGHT",
    WALK_HOLD_DOWN: "WALK_HOLD_DOWN",
    WALK_HOLD_UP: "WALK_HOLD_UP",
    WALK_HOLD_LEFT: "WALK_HOLD_LEFT",
    WALK_HOLD_RIGHT: "WALK_HOLD_RIGHT",
    LIFT_DOWN: "LIFT_DOWN",
    LIFT_UP: "LIFT_UP",
    LIFT_LEFT: "LIFT_LEFT",
    LIFT_RIGHT: "LIFT_RIGHT",
    HURT_DOWN: "HURT_DOWN",
    HURT_UP: "HURT_UP",
    HURT_LEFT: "HURT_LEFT",
    HURT_RIGHT: "HURT_RIGHT",
    DIE_DOWN: "DIE_DOWN",
    DIE_UP: "DIE_UP",
    DIE_LEFT: "DIE_LEFT",
    DIE_RIGHT: "DIE_RIGHT",
} as const;
